apiVersion: ingress.jpmc.com/v1alpha1
kind: Fleet
metadata:
  name: bb4293ee-a9ce-4afd-8a5b-ced01d1e55b3
  namespace: ingress-system
  labels:
    app.kubernetes.io/managed-by: management-api
spec:
  gatewayType: envoy
  replicas: 4
  nodes:
    - name: "bb4293ee-a9ce-4afd-8a5b-ced01d1e55b3-envoy-1"
      index: 1
      datacenter: "us-east-2"
      region: "us-east-2"
      status: "running"
    - name: "bb4293ee-a9ce-4afd-8a5b-ced01d1e55b3-envoy-2"
      index: 2
      datacenter: "eu-west-1"
      region: "eu-west-1"
      status: "running"
    - name: "bb4293ee-a9ce-4afd-8a5b-ced01d1e55b3-envoy-3"
      index: 3
      datacenter: "ap-southeast-1"
      region: "ap-southeast-1"
      status: "running"
    - name: "bb4293ee-a9ce-4afd-8a5b-ced01d1e55b3-envoy-4"
      index: 4
      datacenter: "us-east-1"
      region: "us-east-1"
      status: "running"
status:
  phase: Pending
  observedGeneration: 0
